### ISSUE TITLE
Erreur 500

### ISSUE THREAD

**Issue by Bagu** [Pinaute/OctoPrint_FreeMobile-Notifier#8]
Bonjour,

Le plugin ne fonctionne plus du tout :
`2022-04-21 13:35:25,040 - octoprint.plugins.freemobilenotifier - ERROR - SMS notification error: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_freemobilenotifier/__init__.py", line 91, in on_event
    request.urlopen(url)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error`

**Comment by Pinaute** [comment]
Salut @Bagu 
C'est peut-être un problème sur les serveurs du FAI Free, ça peut arriver mais c'est toujours temporaire.
Testé avec la dernière version de octoprint (1.7.3), fonctionne bien.

**Comment by Bagu** [comment]
Bonsoir,

Effectivement free merdouille assez régulièrement sur la passerelle d'envoi de sms.
Serai-t'il envisageable de tenter un renvoi en cas de réception d'une erreur 500 ?
Quitte à ce que le nombre de tentatives de renvoi soit configurable de 0 à x (x restant à définir afin d'être raisonnable)
Merci de vous être penché sur ce problème en tout cas.
